version: '3.8'

services:
  web:
    build: .
    container_name: soterojunior-site
    # ports:
    #   - "80:80"
    expose:
      - 80
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=sotero@topideias.com.br

networks:
    default:
        external:
            name: nginx-proxy